---
version: "3"
services:
  influx:
    image: influxdb:1.8
    container_name: huawei_influx
    ports:
      - 8087:8086
    restart: unless-stopped
    volumes:
      - ./influx_lib:/var/lib/influxdb
  grafana:
    image: grafana/grafana-oss:8.4.7
    ports:
      - 4000:3000
    container_name: huawei_grafana
    restart: unless-stopped
    volumes:
      - ./grafana_lib:/var/lib/grafana
    user: '0'
  huawei:
    image: huawei-to-influx
    container_name: huawei
    environment:
      HUAWEI_ADDRESS: ${HUAWEI_ADDRESS}
      INFLUX_HOST: influx
      INFLUX_PORT: 8086
      INFLUX_USERNAME: ""
      INFLUX_PASSWORD: ""
      INFLUX_DATABASE: grafana
      HUAWEI_SLAVE: 1
